[prnz-wallet]
user = www-data
group = www-data

listen = /run/php/prnz-wallet.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 30s
pm.max_requests = 500

request_terminate_timeout = 30s
php_admin_value[memory_limit] = 128M
php_admin_value[expose_php] = Off
php_admin_flag[display_errors] = off
php_admin_value[error_log] = /var/log/php-fpm/prnz-wallet-error.log
